version: '3.0'
services:
    nodered:
        image: nodered/node-red-docker:rpi
        container_name: nodered
        user: root
        volumes:
            - ./data:/data
        network_mode: "host"
        ports:
            - 1880:1880
        cap_add:
            - SYS_RAWIO
        privileged: true
        tty: true
        devices:
            - /dev/gpiomem
            - /dev/ttyAMA0
